name: "⚠️ Delivery Status Issue"
description: "Use this when there is an issue related to the delivery status/take-down of a release."
title: "[DELIVERY ISSUE]: Release [Release ID]"
labels:
  - "needs-triage"
assignees: []
body:

  - type: markdown
    attributes:
      value: |

        > ℹ️ **Tip:** The more precise the information, the faster we can help.

  - type: input
    id: db-id
    attributes:
      label: "Delivery Bundle ID"
      description: |
        Provide the **id of the delivery bundle** that is failing.

        <details>
        <summary>❓ Click here to see where to find this information</summary>

        ![Screenshot showing location of Release ID/UPC](https://i.ibb.co/FqH91x9y/image.png)
        
        *You can usually find the Release ID or UPC on the main details page for your release in our platform, often located near the release title or in the 'Identifiers' section.*
        </details>
      placeholder: "e.g., 123456"
    validations:
      required: true

  - type: dropdown
    id: current-status
    attributes:
      label: "Current Displayed Status in System"
      description: "What status does our system currently show for this release?"
      options:
        - "In Delivery"
        - "Delivered"
        - "Takedown Processing"
        - "Open"
        - "Cancelled"
        - "Feedback Required"
    validations:
      required: false

  - type: dropdown
    id: expected-status
    attributes:
      label: "Expected Status"
      description: "What status should it have instead?"
      options:
        - "In Delivery"
        - "Delivered"
        - "Takedown Processing"
        - "Open"
        - "Cancelled"
        - "Feedback Required"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        
        This information is the minimum we need, but you might be able to get more information about the root of the issue by checking the deliveries within the delivery bundle mentioned above.
        <details>
        <summary>❓ How to find?</summary>

        ![Screenshot showing location of Release ID/UPC](https://i.ibb.co/qFJWWSr4/image.png)
        
        *See if there is some delivery with a status such as "aggregator rejected" or not completed*
        </details>
  - type: checkboxes
    id: handler-affected
    attributes:
      label: "Handler affected"
      description: "If you do find some delivery failing, select which"
      options:
        - label: "KNM (Kontor)"
        - label: "YTM (Aspera)"
        - label: "YTM (Lambda)"        
        - label: "CID"        
    validations:
      required: false 

  - type: input
    id: delivery-id
    attributes:
      label: "Delivery ID"
      description: |
        Provide the **id of the delivery** that is failing.

        <details>
        <summary>❓ What Id is this?</summary>

        ![Screenshot showing location of Delivery ID](https://i.ibb.co/yF6tHCjq/image.png)
        
        </details>
      placeholder: "e.g., 123456"
    validations:
      required: false

  - type: textarea
    id: error-message
    attributes:
      label: "Error Message Received (if any) 📩" # Unicode emoji
      description: |
        Please copy and paste the **exact error message**, if you see any, inside this delivery.
       
        ```text
        Example: "DOMDocument::schemaValidate(): Element 'c_line': [facet 'pattern'] 
        The value '2020 ' is not accepted by the pattern '((19[0-9][0-9])|(20[0-9][0-9])) [^-\s].*'."
        ```

      placeholder: "Error message"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Info"
      placeholder: "Leave a comment if needed"
    validations:
      required: false
