name: "🚦 Release Status Issue"
description: "Use this form if a specific release has an incorrect status on app/admin"
title: "[RELEASE STATUS]: Incorrect status on Release [Release ID]"
labels:
  - "help wanted"
assignees: []
body:
  - type: input
    id: release-id
    attributes:
      label: "Release ID"
      description: |
        Provide the **Release ID**.

        <details>
        <summary>❓ Click here to see where to find this information</summary>

        ![Screenshot showing location of Release ID/UPC](https://i.ibb.co/M12csLZ/image.png)

        *You can usually find the Release ID or UPC on the main details page for your release in our platform, often located near the release title or in the 'Identifiers' section.*
        </details>
      placeholder: "e.g., 123456"
    validations:
      required: true

  - type: input
    id: db-id
    attributes:
      label: "Delivery Bundle ID"
      description: |
       Provide the **Delivery Bundle ID**.

        <details>
        <summary>❓ Click here to see where to find this information</summary>

        ![Screenshot showing location of Release ID/UPC](https://i.ibb.co/M12csLZ/image.png) # Note: Same image link. Ensure this is correct for both fields.

        *You can usually find the Release ID or UPC on the main details page for your release in our platform, often located near the release title or in the 'Identifiers' section.*
        </details>
      placeholder: "e.g., 123456"
    validations:
      required: true

  - type: dropdown
    id: current-status
    attributes:
      label: "Current Displayed Status in System"
      description: "What status does our system currently show for this release?"
      options:
        - "In Delivery"
        - "Delivered"
        - "Takedown Processing"
        - "Open"
        - "Cancelled"
        - "Feedback Required"
    validations:
      required: false

  - type: dropdown
    id: expected-status
    attributes:
      label: "Expected Status"
      description: "What status should it have instead?"
      options:
        - "In Delivery"
        - "Delivered"
        - "Takedown Processing"
        - "Open"
        - "Cancelled"
        - "Feedback Required"
    validations:
      required: false

  - type: textarea
    id: observed-issue
    attributes:
      label: "Verify Deliveries and add details" 
      description: "Normally, the status will reflect the statuses of it's individual deliveries. For example, if a track has been taken down from YTM but not from KNM, would still shows as taken-down. Paste here the delivery id and give more context about the issue."
      placeholder: "e.g., System shows 'Live' but release not found on Spotify..."
    validations:
      required: true
