name: "🔑 User Email Change Request"
description: "Use this template ONLY to request a change to a user's email address."
title: "[EMAIL CHANGE]: Customer [Customer ID]"
labels:
  - "kratos"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Please provide details for the email change request or issue.**

  - type: input
    id: customer-id
    attributes:
      label: "Customer ID"
      description: "The ID from our system"
      placeholder: "e.g., 123456"
    validations:
      required: true

  - type: input
    id: customer-current-email
    attributes:
      label: "Current Email Address"
      description: "The current email of our customer, to which he should have not have access."
      placeholder: "e.g., current.email@example.com"
    validations:
      required: true

  - type: input
    id: customer-desired-email
    attributes:
      label: ""New" Email Address"
      description: "The desired new email address our customer wants."
      placeholder: "new.email@example.com"
    validations:
      required: false # Not required if it's reporting an issue with an *attempted* change

  - type: textarea
    id: reason-description
    attributes:
      label: "Reason for Change"
      description: "Explain why the email needs to be changed by ourselves and not via the self-service solution provided on our dashboard."
      placeholder: "e.g., User typo during signup, User lost access to old email, Error when attempting to change email."
    validations:
      required: true

  - type: checkboxes
    id: user-confirmation
    attributes:
      label: "User Confirmation (for manual changes)"
      options:
        - label: "User has confirmed this change request (e.g., via email thread, ticket)."
          required: false
        - label: "Proof of identity/ownership verified (if applicable)."
          required: false

  - type: input
    id: reporter-slack-username
    attributes:
      label: "Reporter Slack Username (from v4soldiers)"
      description: "Your Slack username for follow-up questions."
      placeholder: "@yourname"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any other relevant information."
    validations:
      required: false
