name: "🚚 Export/Delivery Failure Report"
description: "Report an issue related to a failure in exporting a release, either delivering or taking-down."
title: "[DELIVERY FAILURE]: Release [Release ID] failed to export/deliver"
labels:
  - "needs-triage"
assignees: []
body:

  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible about the export or delivery failure. This will help us investigate and resolve the issue quickly!

        > ℹ️ **Tip:** The more precise the information, the faster we can help.

  - type: input
    id: db-id
    attributes:
      label: "Release ID"
      description: |
        Provide the **id of the delivery bundle** containing the delivery that is failing.

        <details>
        <summary>❓ Click here to see where to find this information</summary>

        ![Screenshot showing location of Release ID/UPC](https://i.ibb.co/M12csLZ/image.png)
        
        *You can usually find the Release ID or UPC on the main details page for your release in our platform, often located near the release title or in the 'Identifiers' section.*
        </details>
      placeholder: "e.g., 123456"
    validations:
      required: true

  - type: checkboxes
    id: handler-affected
    attributes:
      label: "Handler affected"
      description: "Select the ones that are failing"
      options:
        - label: "KNM (Kontor)"
        - label: "YTM (Aspera)"
        - label: "YTM (Lambda)"        
        - label: "CID"        
    validations:
      required: false 

  - type: textarea
    id: error-message
    attributes:
      label: "Error Message Received (if any) 📩" # Unicode emoji
      description: |
        Please copy and paste the **exact error message**.
        If no error message was shown, describe what happened when you expected the error.
        ```text
        Example: "Failed due to metadata mismatch: track 3 artist name"
        ```
      placeholder: "e.g., 'Failed due to metadata mismatch: track 3 artist name'"
    validations:
      required: false

  - type: input
    id: attempt-date # Assuming this was your next field for 'Date of Attempted Delivery/Export'
    attributes:
      label: "Date of Attempted Delivery/Export 📅" # Unicode emoji for calendar
      description: "When was the delivery or export attempted?"
      placeholder: "YYYY-MM-DD"
    validations:
      required: false

  - type: textarea
    id: expected-outcome
    attributes:
      label: "Expected Outcome"
      description: "What did you expect to happen?"
      placeholder: "The release should be successfully delivered to the specified platform."
    validations:
      required: true

  - type: textarea
    id: error-message2
    attributes:
      label: "Error Message Received (if any) 📩" # Unicode emoji
      description: |
        Please copy and paste the **exact error message**.
        If no error message was shown, describe what happened when you expected the error.
        ```text
        Example: "Failed due to metadata mismatch: track 3 artist name"
        ```
      placeholder: "e.g., 'Failed due to metadata mismatch: track 3 artist name'"
    validations:
      required: false

  - type: textarea
    id: actual-outcome
    attributes:
      label: "Actual Outcome"
      description: "What actually happened?"
      placeholder: "The delivery failed with an error / The release is not appearing on the platform."
    validations:
      required: true

  - type: input
    id: reporter-slack-username
    attributes:
      label: "Reporter Slack Username (from v4soldiers)"
      description: "Your Slack username for follow-up questions."
      placeholder: "@yourname"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context / Screenshots"
      description: "Add any other context about the problem here. You can drag and drop screenshots."
    validations:
      required: false
