name: "🚚 Export/Delivery Failure Report"
description: "Report an issue related to a failure in exporting a release, either delivering or taking-down."
title: "[DELIVERY FAILURE]: Release [Release ID] failed to export/deliver"
labels:
  - "needs-triage"
assignees: []
body:

  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible about the export or delivery failure. This will help us investigate and resolve the issue quickly!

        > ℹ️ **Tip:** The more precise the information, the faster we can help.

  - type: input
    id: db-id
    attributes:
      label: "Delivery Bundle ID"
      description: |
        Provide the **id of the delivery bundle** containing the delivery that is failing.

        <details>
        <summary>❓ Click here to see where to find this information</summary>

        ![Screenshot showing location of Release ID/UPC](https://i.ibb.co/M12csLZ/image.png)
        
        *You can usually find the Release ID or UPC on the main details page for your release in our platform, often located near the release title or in the 'Identifiers' section.*
        </details>
      placeholder: "e.g., 123456"
    validations:
      required: true

  - type: checkboxes
    id: handler-affected
    attributes:
      label: "Handler affected"
      description: "Select the ones that are failing"
      options:
        - label: "KNM (Kontor)"
        - label: "YTM (Aspera)"
        - label: "YTM (Lambda)"        
        - label: "CID"        
    validations:
      required: false 

  - type: input
    id: delivery-id
    attributes:
      label: "Delivery ID"
      description: |
        Provide the **id of the delivery** that is failing.

        <details>
        <summary>❓ Click here to see where to find this information</summary>

        ![Screenshot showing location of Release ID/UPC](https://i.ibb.co/M12csLZ/image.png)
        
        *You can usually find the Release ID or UPC on the main details page for your release in our platform, often located near the release title or in the 'Identifiers' section.*
        </details>
      placeholder: "e.g., 123456"
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: "Error Message Received (if any) 📩" # Unicode emoji
      description: |
        Please copy and paste the **exact error message**.
        If no manifest file is available please write 'No manifest'.
        ```text
        Example: "DOMDocument::schemaValidate(): Element 'c_line': [facet 'pattern'] 
        The value '2020 ' is not accepted by the pattern '((19[0-9][0-9])|(20[0-9][0-9])) [^-\s].*'."
        ```
        <details>
        <summary>❓ Click here to see where to find this information</summary>

        ![Screenshot showing location of Release ID/UPC](https://i.ibb.co/M12csLZ/image.png)
        
        *You can usually find the Release ID or UPC on the main details page for your release in our platform, often located near the release title or in the 'Identifiers' section.*
        </details>
      placeholder: "e.g., 'Failed due to metadata mismatch: track 3 artist name'"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Info"
      placeholder: "Leave a comment if needed"
    validations:
      required: false
