name: "🚦 Release Status Issue"
description: "Use this form if a specific release has an incorrect status on app/admin"
title: "[RELEASE STATUS]: Incorrect status on Release [Release ID]"
labels:
  - "help wanted"
assignees: []
body:
  - type: input
    id: release-id
    attributes:
      label: "Release ID"
      description: |
        Provide the **id of the delivery bundle** containing the delivery that is failing.

        <details>
        <summary>❓ Click here to see where to find this information</summary>

        ![Screenshot showing location of Release ID/UPC](https://i.ibb.co/M12csLZ/image.png)

        *You can usually find the Release ID or UPC on the main details page for your release in our platform, often located near the release title or in the 'Identifiers' section.*
        </details>
      placeholder: "e.g., 123456"
    validations:
      required: true

  - type: input
    id: db-id # Changed from release-id to db-id as it was duplicated, assuming this was intended for Delivery Bundle ID
    attributes:
      label: "Delivery Bundle ID"
      description: |
        Provide the **id of the delivery bundle** containing the delivery that is failing. # Note: This description is identical to the one for 'release-id'. You might want to differentiate them.

        <details>
        <summary>❓ Click here to see where to find this information</summary>

        ![Screenshot showing location of Release ID/UPC](https://i.ibb.co/M12csLZ/image.png) # Note: Same image link. Ensure this is correct for both fields.

        *You can usually find the Release ID or UPC on the main details page for your release in our platform, often located near the release title or in the 'Identifiers' section.*
        </details>
      placeholder: "e.g., 123456" # Note: Same placeholder.
    validations:
      required: true

  - type: dropdown
    id: current-status
    attributes:
      label: "Current Displayed Status in System"
      description: "What status does our system currently show for this release?"
      options:
        - "In Delivery"
        - "Delivered"
        - "Takedown Processing"
        - "Open"
        - "Cancelled"
        - "Feedback Required"
    validations:
      required: false # Changed to false as it's a 'current' status query, might not always be applicable to be 'required'

  - type: dropdown
    id: expected-status
    attributes:
      label: "Expected Status"
      description: "What status should it have instead?"
      options:
        - "In Delivery"
        - "Delivered"
        - "Takedown Processing"
        - "Open"
        - "Cancelled"
        - "Feedback Required"
    validations:
      required: false # Changed to false, an expected status might not always be known or required for an initial report

  - type: textarea
    id: observed-issue # Corrected what seemed like a typo from "VErify the Deliveries" label to a more suitable ID
    attributes:
      label: "Observed Issue / Discrepancy" # Changed label from "VErify the Deliveries"
      description: "Describe the problem. e.g., System shows 'Live' but release not found on Spotify; Status stuck on 'Processing' for 3 days; Received 'Error' status with no details. Statuses will normally reflect information from the individual deliveries contained within a Delivery Bundle."
      placeholder: "e.g., System shows 'Live' but release not found on Spotify..."
    validations:
      required: true

  - type: input
    id: specific-platforms
    attributes:
      label: "Specific Platform(s) (if issue is platform-dependent)"
      description: "If the issue is only on certain DSPs, list them here."
      placeholder: "e.g., Spotify, Deezer"
    validations:
      required: false

  - type: input
    id: submission-date
    attributes:
      label: "Date of Submission / Last Known Status Update"
      description: "When was the release submitted or when did the status last change?"
      placeholder: "YYYY-MM-DD"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context / Screenshots"
      description: "e.g., Link to release on DSP if found, screenshots of error messages."
      placeholder: "Add any other relevant details or links here." # Added a placeholder
    validations:
      required: false
