name: "🚦 Release Status Issue"
description: "Use this form if a specific release has an incorrect status on app/admin"
title: "[RELEASE STATUS]: Incorrect status on Release [Release ID]"
labels:
  - "help wanted"
assignees: []
body:

  - type: input
    id: release-id
    attributes:
      label: "Release ID"
      description: |
        
        <details>
        <summary>❓ Click here to see where to find this information</summary>

        ![Screenshot showing location of Release ID/UPC](https://i.ibb.co/M12csLZ/image.png)
        
        *You can usually find the Release ID or UPC on the main details page for your release in our platform, often located near the release title or in the 'Identifiers' section.*
        </details>
      placeholder: "e.g., 123456"
    validations:
      required: true

    - type: input
      id: deliverybundle-id
      attributes:
        label: "Delivery Bundle ID"
        description: |
        
        <details>
        <summary>❓ Click here to see where to find this information</summary>

        ![Screenshot showing location of Release ID/UPC](https://i.ibb.co/M12csLZ/image.png)
        
        *You can usually find the Release ID or UPC on the main details page for your release in our platform, often located near the release title or in the 'Identifiers' section.*
        </details>
      placeholder: "e.g., 123456"
    validations:
      required: true

  - type: dropdown
    id: current-status
    attributes:
      label: "Current Displayed Status in System"
      description: "What status does our system currently show for this release?"
      options:
        - "In Delivery"
        - "Delivered"
        - "Takedown Processing"
        - "Open"
        - "Cancelled"
        - "Feedback Required"
    validations:
      required: false

    - type: dropdown
    id: expected-status
    attributes:
      label: "Expected Status"
      description: "What status should have instead?"
      options:
        - "In Delivery"
        - "Delivered"
        - "Takedown Processing"
        - "Open"
        - "Cancelled"
        - "Feedback Required"
    validations:
      required: false    

  - type: textarea
    id: observed-issue
    attributes:
      label: "VErify the Deliveries"
      description: "Statuses will normally reflect information from the individual deliveries contained within a Delivery Bundle"
      placeholder: "e.g., System shows 'Live' but release not found on Spotify; Status stuck on 'Processing' for 3 days; Received 'Error' status with no details."
    validations:
      required: true

  - type: input
    id: specific-platforms
    attributes:
      label: "Specific Platform(s) (if issue is platform-dependent)"
      description: "If the issue is only on certain DSPs, list them here."
      placeholder: "e.g., Spotify, Deezer"
    validations:
      required: false

  - type: input
    id: submission-date
    attributes:
      label: "Date of Submission / Last Known Status Update"
      description: "When was the release submitted or when did the status last change?"
      placeholder: "YYYY-MM-DD"
    validations:
      required: false

  - type: input
    id: reporter-slack-username
    attributes:
      label: "Reporter Slack Username (from v4soldiers)"
      description: "Your Slack username for follow-up questions."
      placeholder: "@yourname"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context / Screenshots"
      description: "e.g., Link to release on DSP if found, screenshots of error messages."
    validations:
      required: false
