name: Export/Delivery issue
description: Report an issue with deliveries
title: "[Export/Delivery] "
labels: ["bug", "export"]
assignees:
  - octocat # Replace with actual usernames if desired
body:
  - type: markdown
    attributes:
      value: |
        We're sorry about the issue. Let's get it fixed!
        Please provide as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Provide a clear and concise description of what the visual bug is.
      placeholder: "Example: The main login button is overlapping the text field on smaller screens."
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps To Reproduce
      description: Detail the exact steps needed to see the bug.
      placeholder: |
        1. Navigate to the 'Login' page.
        2. Resize the browser window to be less than 600px wide.
        3. Observe the button placement.
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen or see?
      placeholder: "Example: The login button should stay below the text field without overlapping."
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser(s) Affected
      description: Which browser(s) did you experience the issue in?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Brave
        - Other (Please specify in Additional Context)
    validations:
      required: false # Make true if you always need this info
  - type: input
    id: screen-resolution
    attributes:
      label: Screen Resolution (Optional)
      description: If relevant, provide the screen resolution where you saw the issue (e.g., 1920x1080).
      placeholder: "e.g., 1920x1080"
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screencasts
      description: Please add screenshots or links to screencasts (e.g., Loom, Giphy) demonstrating the problem. This is extremely helpful!
    validations:
      required: false
